<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    private function content(string $type, string $en, string $id): array
    {
        return [
            'en' => ['type' => $type, 'text' => $en],
            'id' => ['type' => $type, 'text' => $id],
        ];
    }

    public function run(): void
    {
        $posts = [
            [
                'slug' => 'why-indonesian-coffee-deserves-a-name',
                'category' => 'origin',
                'cover' => '/images/blog-1.jpg',
                'title' => ['en' => 'Why Indonesian coffee deserves a name', 'id' => 'Mengapa kopi Indonesia pantas memiliki nama'],
                'excerpt' => ['en' => 'For decades, the best Indonesian lots were blended away into nameless bulk. We think that has to change.', 'id' => 'Selama puluhan tahun, lot terbaik Indonesia hilang dalam campuran tanpa nama. Kami rasa itu harus berubah.'],
                'content' => [
                    $this->content('p', 'Walk into any roastery in Europe or North America and you will find coffees from Ethiopia, Colombia, Kenya — named, traced, and celebrated. Their origin appears on the bag, their producers are credited, and their cup profiles are discussed in cupping rooms around the world. Indonesia, one of the largest coffee producers on earth and a country whose growing regions span volcanic archipelagos from Aceh to Papua, is still often sold as a seasoning for blends. When the words "Sumatra" or "Java" do appear, they usually describe a dark-roasted blending component rather than a named, traceable origin.', 'Masuki roastery mana pun di Eropa atau Amerika Utara dan Anda akan menemukan kopi dari Ethiopia, Kolombia, Kenya — bernama, terlacak, dan dirayakan. Asal-usulnya tertera di kemasan, produsennya disebut namanya, dan profil cangkirnya dibahas di ruang cupping di seluruh dunia. Indonesia, salah satu produsen kopi terbesar di dunia dan negara yang wilayah tanamnya membentang di kepulauan vulkanik dari Aceh hingga Papua, masih sering dijual sebagai bumbu campuran. Ketika kata "Sumatra" atau "Java" muncul, biasanya itu menggambarkan komponen campuran dengan roast gelap, bukan origin yang bernama dan terlacak.'),
                    $this->content('p', 'The highlands around Lake Toba grow Arabica of real character: dense, sweet, low in acidity, with a heavy body that carries through milk and espresso alike. Grown on volcanic soil at 1,300–1,600 metres above sea level and processed with the traditional giling basah method, these beans are unmistakable once you cup them side by side with other origins. The problem was never the coffee. The problem was that nobody gave it a name — and a coffee without a name is a coffee without a market identity, a quality premium, or a farmer who gets credited for it.', 'Dataran tinggi di sekitar Danau Toba menumbuhkan Arabika berkarakter sejati: padat, manis, rendah keasaman, dengan body pekat yang tetap terasa di susu maupun espresso. Tumbuh di tanah vulkanik pada ketinggian 1.300–1.600 meter di atas permukaan laut dan diolah dengan metode giling basah tradisional, biji ini tak salah kenali begitu Anda mencicipinya berdampingan dengan origin lain. Masalahnya bukan kopinya. Masalahnya tak ada yang memberinya nama — dan kopi tanpa nama adalah kopi tanpa identitas pasar, tanpa premium mutu, dan tanpa petani yang diakui.'),
                    $this->content('h2', 'What changes when coffee has a name', 'Yang berubah ketika kopi punya nama'),
                    $this->content('p', 'Traceability means the farmer is paid for quality, not anonymised into a blend price. When a lot can be traced back to a named village, the person who grew it can finally be rewarded for careful picking, proper fermentation, and patient drying. It means the buyer can verify origin, altitude, and process with a single request instead of taking a broker\'s word for it. And it means the drinker can finally taste the place — the volcanic soil, the cool highland nights, the hands that sorted the cherries — not just a generic "dark roast" blended from whoever sold the cheapest beans that season.', 'Keterlacakan berarti petani dibayar untuk mutu, bukan dianonimkan ke harga campuran. Ketika sebuah lot bisa ditelusuri ke desa yang bernama, orang yang menanamnya akhirnya bisa dihargai untuk pemetikan yang teliti, fermentasi yang tepat, dan penjemuran yang sabar. Itu berarti pembeli dapat memverifikasi asal, ketinggian, dan proses dengan satu permintaan, tanpa hanya mengandalkan perkataan broker. Dan itu berarti penikmat akhirnya bisa merasakan tempatnya — tanah vulkanik, malam dingin di dataran tinggi, tangan-tangan yang memilah ceri — bukan sekadar "dark roast" generik dari campuran siapa pun yang menjual biji termurah musim itu.'),
                    $this->content('p', 'Naming also changes the economics of an entire region. Origins that are marketed well earn premiums that get reinvested in better drying beds, sorting stations, and farming practice. The more a region is known, the more buyers compete for its lots, and the more stable farm-gate prices become. That virtuous cycle only starts when someone decides the coffee deserves a name on the bag.', 'Pemberian nama juga mengubah ekonomi sebuah wilayah. Origin yang dipasarkan dengan baik memperoleh premium yang diinvestasikan kembali ke drying bed yang lebih baik, stasiun sortasi, dan praktik bertani. Semakin dikenal sebuah wilayah, semakin ketat pembeli bersaing untuk lot-nya, dan semakin stabil harga di tingkat kebun. Siklus positif itu hanya dimulai ketika seseorang memutuskan bahwa kopi itu pantas mendapatkan nama di kemasannya.'),
                    $this->content('h2', 'Indonesia is ready for its close-up', 'Indonesia siap tampil di panggung depan'),
                    $this->content('p', 'The specialty market has spent two decades discovering single origins — first Ethiopia and Kenya, then Colombia and Central America, then the naturals of Brazil and the new wave of Chinese and Vietnamese micro-lots. Indonesia\'s turn has been coming for a while, and the demand is clearly there: roasters are hungry for low-acid, big-body coffees that stand up to milk and espresso, and Sumatran Arabica delivers exactly that.', 'Pasar spesialti telah menghabiskan dua dekade untuk menemukan single origin — pertama Ethiopia dan Kenya, lalu Kolombia dan Amerika Tengah, kemudian natural dari Brasil dan gelombang baru micro-lot dari Tiongkok dan Vietnam. Giliran Indonesia sebenarnya sudah lama dinanti, dan permintaannya jelas ada: para roaster menginginkan kopi rendah asam dengan body besar yang kuat di susu dan espresso, dan Arabika Sumatra memberikan persis itu.'),
                    $this->content('p', 'What is missing is not quality — it is identity. Thousands of Indonesian smallholders grow exceptional coffee, but few of them have a route to a market that knows their name. That is the work we do at Given Coffee: keeping every lot traceable from a named farm in Lintong Nihuta and Doloksanggul to a named roastery abroad — and giving Indonesian coffee the name it always deserved.', 'Yang hilang bukanlah mutu — melainkan identitas. Ribuan petani kecil Indonesia menanam kopi luar biasa, tetapi hanya sedikit dari mereka yang memiliki jalur ke pasar yang mengenal nama mereka. Itulah kerja kami di Given Coffee: menjaga setiap lot terlacak dari kebun yang bernama di Lintong Nihuta dan Doloksanggul hingga roastery yang bernama di luar negeri — dan memberi kopi Indonesia nama yang selalu pantas ia dapatkan.'),
                ],
                'published_at' => now()->subDays(20),
            ],
            [
                'slug' => 'the-washed-process-explained',
                'category' => 'process',
                'cover' => '/images/blog-2.jpg',
                'title' => ['en' => 'The wet-hulled process, explained', 'id' => 'Proses giling basah, dijelaskan'],
                'excerpt' => ['en' => 'Why is our Lintong lot so low in acidity and heavy in body? A short guide to Sumatra\'s signature wet-hulled process.', 'id' => 'Mengapa lot Lintong kami rendah keasaman dan berbody pekat? Panduan singkat proses giling basah khas Sumatra.'],
                'content' => [
                    $this->content('p', 'Coffee processing is how the fruit around the bean is removed and the bean prepared for drying and storage. There are many methods practised around the world — washed, natural, honey — and each one leaves a fingerprint on the final cup. Sumatra is famous for one method above all: giling basah, or wet hulling. It is practised widely across the island, it is the reason Sumatran coffee tastes like nothing else on earth, and it is very often misunderstood by buyers who meet it only through a spec sheet.', 'Pengolahan kopi adalah cara buah di sekitar biji dibuang dan biji disiapkan untuk dikeringkan dan disimpan. Ada banyak metode yang dipraktikkan di seluruh dunia — washed, natural, honey — dan masing-masing meninggalkan sidik jari pada cangkir akhir. Sumatra terkenal dengan satu metode di atas segalanya: giling basah. Metode ini dipraktikkan secara luas di seluruh pulau, menjadi alasan kopi Sumatra terasa seperti tidak ada duanya di dunia, dan sangat sering disalahpahami oleh pembeli yang hanya mengenalnya lewat spec sheet.'),
                    $this->content('p', 'Understanding giling basah matters for anyone buying Sumatran coffee, because it explains everything you taste in the cup: the low acidity, the heavy syrupy body, the herbal and earthy complexity, and even the distinctive bluish-green colour of the raw beans. Once you know what happened on the farm and at the mill, the coffee stops being a mystery and becomes a predictable, buyable product.', 'Memahami giling basah penting bagi siapa pun yang membeli kopi Sumatra, karena metode ini menjelaskan semua yang Anda rasakan di cangkir: keasaman rendah, body pekat seperti sirup, kompleksitas herbal dan earthy, bahkan warna hijau kebiruan yang khas pada biji mentahnya. Begitu Anda tahu apa yang terjadi di kebun dan di pabrik, kopi tidak lagi menjadi misteri dan berubah menjadi produk yang dapat diprediksi dan layak dibeli.'),
                    $this->content('h2', 'The steps', 'Langkah-langkahnya'),
                    $this->content('p', 'Ripe cherries are picked by hand — usually in several passes over the same trees, because cherries on one branch ripen at different times — then pulped the same day to remove the outer skin. The beans are fermented overnight to break down the sticky mucilage layer, washed clean, and dried in their parchment until the moisture drops to around 30–40%. At this point the bean is still soft and moist inside its protective hull.', 'Ceri matang dipetik dengan tangan — biasanya dalam beberapa tahap di pohon yang sama, karena ceri di satu cabang matang pada waktu berbeda — lalu dikupas di hari yang sama untuk membuang kulit luarnya. Biji difermentasi semalam untuk menguraikan lapisan lendir yang lengket, dicuci bersih, lalu dijemur dalam parchment hingga kadar air turun ke sekitar 30–40%. Pada titik ini biji masih lembut dan lembap di dalam kulit tanduk pelindungnya.'),
                    $this->content('p', 'This is where the method diverges from everything else. In a washed process, the bean is dried in its parchment all the way down to 10–12% and only then hulled. In giling basah, the parchment is hulled off while the bean is still at 30–40% moisture — still soft, still wet — and the naked bean is then spread out to finish drying. That single decision, hulling early, changes the entire character of the coffee.', 'Di sinilah metode ini berbeda dari semuanya. Dalam proses washed, biji dikeringkan dalam parchment sampai turun ke 10–12% dan baru kemudian dikupas. Dalam giling basah, kulit tanduk dibuang saat biji masih berada di kadar air 30–40% — masih lembut, masih basah — dan biji telanjang kemudian dihamparkan untuk menyelesaikan pengeringan. Satu keputusan itu, mengupas lebih awal, mengubah seluruh karakter kopi.'),
                    $this->content('h2', 'What it does to the cup', 'Efeknya pada cangkir'),
                    $this->content('p', 'Hulling the bean in this semi-wet state gives it its bluish-green tint, lowers acidity, and boosts body — the classic Sumatran cup. The early removal of the parchment exposes the bean to the air and to whatever is in it, including local microbes and humidity, which accelerates fermentation-like changes in the seed. The result is a coffee that is dense, earthy, herbal, and almost syrupy in texture, with far less bright acidity than a washed coffee from the same altitude.', 'Mengupas biji dalam kondisi semi-lembap inilah yang memberi warna kebiruan, menurunkan keasaman, dan menambah body — cangkir khas Sumatra. Pembuangan parchment lebih awal membuat biji terpapar udara dan segala isinya, termasuk mikroba dan kelembapan lokal, yang mempercepat perubahan seperti fermentasi pada biji. Hasilnya adalah kopi yang padat, earthy, herbal, dan hampir bersirup teksturnya, dengan keasaman cerah yang jauh lebih rendah daripada kopi washed dari ketinggian yang sama.'),
                    $this->content('p', 'This is also why our Lintong lot tastes the way it does. The 85.5+ SCA score on the current crop is carried by sweetness and body rather than by bright fruit — it is a coffee built for espresso and milk, for blending with brighter origins, or for drinkers who simply prefer a heavy, low-acid cup. Once you understand giling basah, none of that comes as a surprise.', 'Ini juga sebabnya lot Lintong kami terasa seperti ini. Skor SCA 85,5+ pada panen saat ini ditopang oleh rasa manis dan body, bukan oleh buah yang cerah — kopi ini dibangun untuk espresso dan susu, untuk dicampur dengan origin yang lebih cerah, atau untuk penikmat yang sekadar menyukai cangkir pekat rendah asam. Begitu Anda memahami giling basah, semua itu tidak lagi mengejutkan.'),
                ],
                'published_at' => now()->subDays(10),
            ],
            [
                'slug' => 'what-buyers-look-for-in-specialty-lots',
                'category' => 'market',
                'cover' => '/images/blog-3.jpg',
                'title' => ['en' => 'What buyers look for in specialty lots', 'id' => 'Yang dicari pembeli dalam lot spesialti'],
                'excerpt' => ['en' => 'Cupping score, moisture, screen size, documentation — a practical checklist for sourcing green coffee.', 'id' => 'Skor cupping, kadar air, screen size, dokumentasi — daftar praktis untuk mencari green coffee.'],
                'content' => [
                    $this->content('p', 'Buying green coffee for a roastery is different from buying for a supermarket. When you roast and sell coffee under your own name, every defect in the raw material ends up in your cup — and in your reputation. The buyers we work with do not buy on price or on a pretty bag. They buy on a handful of verifiable numbers, and they check them in a consistent order.', 'Membeli green coffee untuk roastery berbeda dengan membeli untuk supermarket. Ketika Anda menyangrai dan menjual kopi atas nama Anda sendiri, setiap cacat pada bahan mentah akan berakhir di cangkir Anda — dan di reputasi Anda. Pembeli yang kami layani tidak membeli berdasarkan harga atau kemasan yang cantik. Mereka membeli berdasarkan segelintir angka yang terverifikasi, dan mereka memeriksanya dalam urutan yang konsisten.'),
                    $this->content('p', 'The good news for roasters is that the checklist is short, learnable, and nearly all of it can be confirmed before a container leaves origin. The good news for exporters is that a lot which passes this checklist earns a premium and long-term buyers. Here is what serious buyers check, in the order they check it.', 'Kabar baik bagi roaster adalah daftarnya pendek, bisa dipelajari, dan hampir semuanya dapat dikonfirmasi sebelum kontainer meninggalkan origin. Kabar baik bagi eksportir adalah lot yang lulus daftar ini mendapatkan premium dan pembeli jangka panjang. Inilah yang diperiksa pembeli serius, secara berurutan.'),
                    $this->content('h2', '1. Cupping score', '1. Skor cupping'),
                    $this->content('p', 'A lot scoring 84+ (SCA) commands a premium because it is consistent and drinkable on its own. That threshold matters: 80–84 is good commercial specialty, while 84+ is where coffee stops being a commodity and becomes a product a roaster can build a menu around. Always ask for the full cupping report — the flavour notes, the breakdown of the score sheet, the date it was cupped — not just the headline number. A report without a date tells you nothing about the lot you are actually buying.', 'Lot dengan skor 84+ (SCA) berharga premium karena konsisten dan enak diminum sendiri. Ambang batas itu penting: 80–84 adalah spesialti komersial yang baik, sementara 84+ adalah titik di mana kopi berhenti menjadi komoditas dan menjadi produk yang bisa dibangun menu oleh roaster. Selalu minta laporan cupping lengkap — catatan rasa, rincian lembar skor, tanggal cupping — bukan sekadar angka utamanya. Laporan tanpa tanggal tidak memberi tahu apa pun tentang lot yang sebenarnya Anda beli.'),
                    $this->content('h2', '2. Moisture and screen size', '2. Kadar air dan screen size'),
                    $this->content('p', 'Green beans should ship at 10.5–11.5% moisture. Anything higher risks mold, mustiness, and ochratoxin during weeks of ocean transit in a humid container. Anything lower risks stale, brittle beans that cup flat and lose their aromatics before they even reach your roaster. Both problems are invisible to the eye, so buyers verify with a moisture meter reading on the actual lot — not on the brochure.', 'Green bean harus dikirim dengan kadar air 10,5–11,5%. Lebih tinggi berisiko jamur, apek, dan okratoksin selama berminggu-minggu pelayaran dalam kontainer yang lembap. Lebih rendah berisiko biji kering dan rapuh yang terasa flat dan kehilangan aromatiknya bahkan sebelum tiba di roaster Anda. Kedua masalah itu tak terlihat oleh mata, sehingga pembeli memverifikasi dengan pembacaan moisture meter pada lot sebenarnya — bukan pada brosur.'),
                    $this->content('p', 'Screen size is a quick quality proxy. A lot that is mostly screen 18 and above indicates good bean development and consistent sorting; a lot full of small beans and broken pieces suggests the farm or mill cut corners. It is not a flavour measure, but it is a fast, honest signal about how much care went into the lot.', 'Screen size adalah proksi mutu yang cepat. Lot yang sebagian besar berukuran screen 18 ke atas menunjukkan perkembangan biji yang baik dan sortasi yang konsisten; lot yang penuh biji kecil dan pecahan menandakan kebun atau pabrik memotong jalan pintas. Ini bukan ukuran rasa, tetapi sinyal yang cepat dan jujur tentang seberapa besar perhatian yang diberikan pada lot tersebut.'),
                    $this->content('h2', '3. Documentation', '3. Dokumentasi'),
                    $this->content('p', 'Phytosanitary certificate, certificate of origin, invoice, packing list — if the paperwork is easy, the shipment will be too. Documentation is the first sign of a serious exporter, because it is the part of the business that cannot be faked with good beans. An exporter who has its documents in order has clearly shipped before, has survived customs at both ends, and knows how to get a container from a farm in the highlands to a port on the other side of the world.', 'Sertifikat phytosanitary, certificate of origin, invoice, packing list — jika dokumennya rapi, kirimannya juga akan rapi. Dokumentasi adalah tanda pertama eksportir yang serius, karena ini adalah bagian bisnis yang tidak bisa dipalsukan dengan biji yang bagus. Eksportir yang dokumennya beres jelas sudah pernah mengirim sebelumnya, selamat melalui bea cukai di kedua ujung, dan tahu cara membawa kontainer dari kebun di dataran tinggi ke pelabuhan di seberang dunia.'),
                    $this->content('p', 'Finally, buyers look for the things that are hardest to put on a checklist: consistency across shipments and honesty when something goes wrong. A lot that arrived slightly off spec last time and an exporter who said so and made it right is worth more than a perfect lot from a supplier who disappears when there is a problem. That relationship trust is the real product of specialty coffee trade.', 'Terakhir, pembeli mencari hal-hal yang paling sulit ditaruh di daftar: konsistensi antar kiriman dan kejujuran ketika ada yang tidak beres. Lot yang tiba sedikit meleset dari spesifikasi terakhir kali dan eksportir yang mengatakannya serta memperbaikinya lebih berharga daripada lot sempurna dari pemasok yang menghilang ketika ada masalah. Kepercayaan hubungan itulah produk sejati dari perdagangan kopi spesialti.'),
                ],
                'published_at' => now()->subDays(3),
            ],
            [
                'slug' => 'from-cherry-to-container',
                'category' => 'process',
                'cover' => '/images/real/cherry.jpg',
                'title' => ['en' => 'From cherry to container', 'id' => 'Dari ceri hingga kontainer'],
                'excerpt' => ['en' => 'Follow one export lot through every stage: picking, fermenting, drying, milling, and loading the container.', 'id' => 'Ikuti satu lot ekspor melalui setiap tahap: petik, fermentasi, jemur, miling, hingga muat kontainer.'],
                'content' => [
                    $this->content('p', 'Every export lot we ship follows the same path, and that path is deliberately uneventful. No shortcuts, no mixing with unknown sources, no last-minute substitutions. When a roaster buys our Lintong lot, the coffee in the container is the coffee we cupped, the coffee we described, and the coffee we photographed at origin. Here is what happens between the farm and the port.', 'Setiap lot ekspor yang kami kirim menempuh jalur yang sama, dan jalur itu sengaja dibuat tanpa kejutan. Tanpa jalan pintas, tanpa campuran dari sumber yang tidak dikenal, tanpa substitusi di menit terakhir. Ketika seorang roaster membeli lot Lintong kami, kopi di dalam kontainer adalah kopi yang kami cupping, yang kami deskripsikan, dan yang kami foto di origin. Inilah yang terjadi antara kebun dan pelabuhan.'),
                    $this->content('p', 'The journey takes weeks, sometimes months, and the quality of the final cup is decided at every single step along the way. A mistake in the drying yard cannot be fixed at the mill. A sloppy sort cannot be fixed at the port. Understanding the full journey helps buyers appreciate why some lots cost more — and why cheap lots are usually cheap for a reason.', 'Perjalanan ini memakan waktu berminggu-minggu, kadang berbulan-bulan, dan mutu cangkir akhir ditentukan di setiap langkah sepanjang jalan. Kesalahan di tempat penjemuran tidak bisa diperbaiki di pabrik. Sortasi yang ceroboh tidak bisa diperbaiki di pelabuhan. Memahami keseluruhan perjalanan membantu pembeli menghargai mengapa sebagian lot lebih mahal — dan mengapa lot murah biasanya murah karena suatu alasan.'),
                    $this->content('h2', 'Picking and fermentation', 'Petik dan fermentasi'),
                    $this->content('p', 'Farmers pick only fully red cherries, usually in several passes over the same trees because the cherries ripen unevenly across weeks. A tree that is stripped in one pass yields a lot full of under-ripe, vegetal beans — the single most common reason a lot cups poorly. Same-day pulping removes the skin while the fruit is still fresh, and an overnight fermentation breaks down the sticky mucilage that coats the bean inside.', 'Petani memetik hanya ceri yang benar-benar merah, biasanya dalam beberapa tahap di pohon yang sama karena ceri matang tidak merata selama berminggu-minggu. Pohon yang dipetik habis dalam sekali lewat menghasilkan lot penuh biji mentah yang berasa vegetal — penyebab paling umum sebuah lot terasa buruk. Pengupasan di hari yang sama membuang kulitnya selagi buah masih segar, dan fermentasi semalam menguraikan lendir lengket yang melapisi biji di dalamnya.'),
                    $this->content('p', 'At this stage the lot is given its identity. Each collection point logs which farms delivered, on what date, and in what quantity. That record follows the coffee for the rest of its journey — it is the backbone of the traceability report we send to buyers with every container.', 'Pada tahap ini lot diberi identitasnya. Setiap titik pengumpulan mencatat kebun mana yang mengirim, pada tanggal berapa, dan dalam jumlah berapa. Catatan itu mengikuti kopi selama sisa perjalanannya — itulah tulang punggung laporan keterlacakan yang kami kirim kepada pembeli bersama setiap kontainer.'),
                    $this->content('h2', 'Drying and wet hulling', 'Pengeringan dan giling basah'),
                    $this->content('p', 'Beans dry on raised patios until the moisture drops to 30–40%, then are hulled while still soft and moist — the giling basah step that defines Sumatran coffee. After wet hulling, the naked beans are spread on tarps or patios to finish drying slowly, down to the shipping target of 10.5–11.5%. This second drying phase is the most weather-dependent part of the whole journey: rain or high humidity means the beans must be covered and moved, which is why the drying season sets the rhythm of the entire export calendar.', 'Biji dijemur di drying bed hingga kadar air turun ke 30–40%, lalu digiling saat masih lembut dan lembap — langkah giling basah yang mendefinisikan kopi Sumatra. Setelah giling basah, biji telanjang dihamparkan di terpal atau tempat penjemuran untuk menyelesaikan pengeringan secara perlahan, hingga target kirim 10,5–11,5%. Fase pengeringan kedua ini adalah bagian paling bergantung cuaca dari seluruh perjalanan: hujan atau kelembapan tinggi berarti biji harus ditutup dan dipindahkan, itulah sebabnya musim kemarau mengatur irama seluruh kalender ekspor.'),
                    $this->content('p', 'Throughout drying, the moisture is checked regularly with calibrated meters. Beans that are bagged too wet will arrive moldy; beans that are dried too hard will arrive brittle and flat. Getting this window right is unglamorous, repetitive work — and it is exactly where premium lots are won or lost.', 'Sepanjang penjemuran, kadar air diperiksa secara rutin dengan meteran terkalibrasi. Biji yang dikemas terlalu basah akan tiba berjamur; biji yang dikeringkan terlalu keras akan tiba rapuh dan flat. Menjaga jendela ini tetap tepat adalah pekerjaan yang tidak glamor dan berulang — dan justru di sinilah lot premium dimenangkan atau hilang.'),
                    $this->content('h2', 'Milling and loading', 'Miling dan pemuatan'),
                    $this->content('p', 'At the warehouse, beans pass through grading screens and hand sorting before being packed in 60kg jute bags with GrainPro hermetic liners. Hand sorting removes defects — black beans, broken beans, stones — that machines cannot judge. The GrainPro liner protects the coffee from moisture and odour during the long sea crossing.', 'Di gudang, biji melewati grading screen dan sortasi tangan sebelum dikemas dalam kantong jute 60kg dengan liner hermetik GrainPro. Sortasi tangan membuang cacat — biji hitam, biji pecah, batu — yang tidak bisa dinilai mesin. Liner GrainPro melindungi kopi dari kelembapan dan bau selama pelayaran panjang.'),
                    $this->content('p', 'The container is lined, loaded, sealed, and documented, and a sample of the exact lot is drawn at the same time for the buyer\'s records. Every bag is numbered, every document is checked twice, and the lot identity — farm records, drying dates, cupping results — travels with the shipment. That paperwork, not the coffee, is what separates an exporter from a middleman.', 'Kontainer dilapisi, dimuat, disegel, dan didokumentasikan, dan sampel dari lot yang persis sama diambil pada waktu yang sama untuk arsip pembeli. Setiap kantong diberi nomor, setiap dokumen diperiksa dua kali, dan identitas lot — catatan kebun, tanggal penjemuran, hasil cupping — ikut dalam kiriman. Dokumen itulah, bukan kopinya, yang membedakan eksportir dari sekadar perantara.'),
                ],
                'published_at' => now()->subDays(5),
            ],
            [
                'slug' => 'lake-toba-volcanic-terroir',
                'category' => 'origin',
                'cover' => '/images/real/Geopark_Caldera_Toba.jpg',
                'title' => ['en' => 'The volcanic terroir of Lake Toba', 'id' => 'Terroir vulkanik Danau Toba'],
                'excerpt' => ['en' => 'Seventy-four thousand years ago, a supervolcano erupted and left behind the most fertile coffee soil in Indonesia.', 'id' => 'Tujuh puluh empat ribu tahun lalu, supervulkan meletus dan meninggalkan tanah kopi paling subur di Indonesia.'],
                'content' => [
                    $this->content('p', 'Lake Toba is not just the largest volcanic lake on earth — it is the reason coffee from this region tastes the way it does. Roughly 74,000 years ago, a supervolcanic eruption reshaped northern Sumatra in an event so large it left ash deposits across the globe. What remained was a caldera that slowly filled with water, ringed by highlands made of mineral-rich volcanic material. It is on those ancient slopes that our partner farms now grow Arabica.', 'Danau Toba bukan sekadar danau vulkanik terbesar di dunia — dialah alasan kopi dari wilayah ini terasa seperti sekarang. Sekitar 74.000 tahun lalu, letusan supervulkan mengubah bentuk Sumatra Utara dalam peristiwa begitu besar hingga meninggalkan endapan abu di seluruh dunia. Yang tersisa adalah kaldera yang perlahan terisi air, dikelilingi dataran tinggi dari material vulkanik kaya mineral. Di lereng purba itulah kebun mitra kami kini menanam Arabika.'),
                    $this->content('p', 'Terroir is an overused word in coffee marketing, but here it is literal. Volcanic soils drain well, hold minerals, and are naturally young in geological terms — which means they are still releasing nutrients to plant roots. Coffee trees growing in this kind of soil have access to a steady, balanced diet that shows up in bean density and cup sweetness.', 'Terroir adalah kata yang terlalu sering dipakai dalam pemasaran kopi, tetapi di sini ia harfiah. Tanah vulkanik memiliki drainase baik, menyimpan mineral, dan secara geologis masih muda — artinya tanah itu masih melepaskan unsur hara ke akar tanaman. Pohon kopi yang tumbuh di tanah semacam ini mendapat asupan yang stabil dan seimbang yang tampak pada kepadatan biji dan rasa manis cangkir.'),
                    $this->content('h2', 'Why altitude matters', 'Mengapa ketinggian penting'),
                    $this->content('p', 'Our partner farms sit at 1,300–1,600 MASL, high enough to feel the temperature swing between day and night that coffee needs. Cool nights slow down cherry maturation, and slow maturation is what lets sugars and acids develop fully inside the fruit. A cherry that ripens over a longer period produces a denser bean with a more complex, sweeter cup than one that is rushed by constant heat.', 'Kebun mitra kami berada di 1.300–1.600 MDPL, cukup tinggi untuk merasakan perbedaan suhu siang-malam yang dibutuhkan kopi. Malam yang dingin memperlambat kematangan ceri, dan kematangan yang lambat itulah yang memungkinkan gula dan asam berkembang sempurna di dalam buah. Ceri yang matang dalam periode lebih lama menghasilkan biji lebih padat dengan cangkir lebih kompleks dan manis daripada ceri yang dipacu oleh panas konstan.'),
                    $this->content('p', 'Altitude also protects the crop in practical ways. The cooler climate reduces pest pressure, which means farmers do not have to lean as heavily on chemical intervention. And the morning mist that rolls off the lake keeps the environment humid enough for the trees while the soil stays well drained. It is a rare combination — plenty of water, but never waterlogged roots.', 'Ketinggian juga melindungi tanaman secara praktis. Iklim yang lebih sejuk mengurangi tekanan hama, yang berarti petani tidak perlu terlalu bergantung pada intervensi kimia. Dan kabut pagi yang bergulung dari danau menjaga lingkungan cukup lembap untuk pohon sementara tanah tetap berdrainase baik. Ini kombinasi langka — air berlimpah, tetapi akar tidak pernah tergenang.'),
                    $this->content('h2', 'The Lintong signature', 'Ciri khas Lintong'),
                    $this->content('p', 'This combination of volcanic soil, altitude, and the giling basah process produces the profile Lintong is known for: cedar and dark chocolate, herbal complexity, and a heavy, syrupy body with low acidity. The soil gives structure and minerality, the altitude gives sweetness and density, and the processing gives the deep, brooding cup character that separates Lintong from higher-acid washed origins.', 'Kombinasi tanah vulkanik, ketinggian, dan proses giling basah ini menghasilkan profil yang membuat Lintong terkenal: cedar dan dark chocolate, kompleksitas herbal, serta body pekat seperti sirup dengan keasaman rendah. Tanah memberi struktur dan mineralitas, ketinggian memberi rasa manis dan kepadatan, dan pengolahan memberi karakter cangkir yang dalam dan kuat yang memisahkan Lintong dari origin washed dengan keasaman lebih tinggi.'),
                    $this->content('p', 'When people ask why they should pay a premium for Lintong Doloksanggul over a cheaper Indonesian blend, this is the answer. The volcanic terroir of the Toba caldera is a fixed, finite asset — no other region can copy it, and no amount of processing skill can fake it. It is the closest thing coffee has to a controlled, natural experiment: same island, same varieties, a specific volcanic bowl, and a cup that cannot be produced anywhere else.', 'Ketika orang bertanya mengapa mereka harus membayar premium untuk Lintong Doloksanggul dibandingkan campuran Indonesia yang lebih murah, inilah jawabannya. Terroir vulkanik kaldera Toba adalah aset tetap dan terbatas — tidak ada wilayah lain yang bisa menirunya, dan tidak ada keterampilan pengolahan yang bisa memalsukannya. Ini adalah hal terdekat yang dimiliki kopi dengan eksperimen alami yang terkendali: pulau yang sama, varietas yang sama, sebuah cekungan vulkanik tertentu, dan cangkir yang tidak bisa diproduksi di tempat lain.'),
                ],
                'published_at' => now()->subDays(7),
            ],
            [
                'slug' => 'lintong-nihuta-doloksanggul-terroir',
                'category' => 'origin',
                'cover' => '/images/add/sorting.jpg',
                'title' => ['en' => 'Lintong Nihuta & Doloksanggul: two names, one cup', 'id' => 'Lintong Nihuta & Doloksanggul: dua nama, satu cangkir'],
                'excerpt' => ['en' => 'What is the difference between Lintong Nihuta and Doloksanggul? Short answer: very little — and that is the point.', 'id' => 'Apa bedanya Lintong Nihuta dan Doloksanggul? Jawaban singkat: hampir tidak ada — dan itu justru intinya.'],
                'content' => [
                    $this->content('p', 'Buyers often ask about the difference between the two names on our labels, and it is a fair question. Lintong is the historical name — it comes from Lintong Nihuta, the sub-district that gave its name to this type of coffee decades ago, back when the coffee was traded through the nearby town of Lintong. Doloksanggul, meanwhile, is the capital town of Humbang Hasundutan, the regency where our partner farms actually sit today. The two names describe the same origin: a stretch of highland on the western rim of the Lake Toba caldera.', 'Pembeli sering bertanya tentang perbedaan kedua nama di label kami, dan itu pertanyaan yang wajar. Lintong adalah nama historis — berasal dari Lintong Nihuta, kecamatan yang memberi nama pada tipe kopi ini puluhan tahun lalu, ketika kopi diperdagangkan melalui kota Lintong di dekatnya. Sementara Doloksanggul adalah ibu kota Humbang Hasundutan, kabupaten tempat kebun mitra kami berada sekarang. Kedua nama itu menggambarkan origin yang sama: bentangan dataran tinggi di tepi barat kaldera Danau Toba.'),
                    $this->content('p', 'Using both names is deliberate. Lintong tells the buyer what to expect in the cup — it is a recognised shorthand for the Sumatran profile, like calling a coffee Yirgacheffe or Huila. Doloksanggul tells the buyer exactly where the truck was loaded. One name for the flavour, one name for the map. Together they give you both the expectation and the address.', 'Penggunaan kedua nama itu disengaja. Lintong memberi tahu pembeli apa yang diharapkan di cangkir — ini singkatan yang dikenal untuk profil Sumatra, seperti menyebut kopi Yirgacheffe atau Huila. Doloksanggul memberi tahu pembeli dengan tepat di mana truk dimuat. Satu nama untuk rasa, satu nama untuk peta. Bersama-sama keduanya memberi Anda ekspektasi sekaligus alamatnya.'),
                    $this->content('h2', 'One variety, several farms', 'Satu varietas, beberapa kebun'),
                    $this->content('p', 'Our lots combine harvests from several smallholder farms growing the same Ateng and Jember varieties under the same conditions. These are not single-estate coffees, and they do not pretend to be. Instead, the model is the strength of the region: hundreds of families farming small plots of volcanic highland, harvesting at the same altitude, processing in the same local style.', 'Lot kami menggabungkan panen dari beberapa kebun petani kecil yang menanam varietas Ateng dan Jember yang sama dalam kondisi yang sama. Ini bukan kopi single-estate, dan tidak berpura-pura menjadi demikian. Justru model inilah kekuatan wilayah: ratusan keluarga menggarap petak kecil di dataran tinggi vulkanik, memanen di ketinggian yang sama, mengolah dengan gaya lokal yang sama.'),
                    $this->content('p', 'Combining their harvests is what makes the profile consistent from container to container. Any single smallholder produces a few hundred kilograms a year — far too little to fill a container, and variable enough that a single farm\'s quirks could swing the whole profile. By combining lots from several farms with the same variety and processing, we average out the variation and deliver a stable, repeatable product. This is how an origin becomes dependable enough for a roaster to build a menu around.', 'Menggabungkan hasil panen mereka itulah yang membuat profil tetap konsisten antar kontainer. Satu petani kecil menghasilkan beberapa ratus kilogram setahun — terlalu sedikit untuk mengisi kontainer, dan cukup bervariasi sehingga keanehan satu kebun bisa mengubah seluruh profil. Dengan menggabungkan lot dari beberapa kebun dengan varietas dan pengolahan yang sama, kami meratakan variasi dan menghadirkan produk yang stabil dan dapat diulang. Beginilah sebuah origin menjadi cukup andal untuk dijadikan dasar menu oleh roaster.'),
                    $this->content('h2', 'Full traceability, on request', 'Keterlacakan penuh, atas permintaan'),
                    $this->content('p', 'Combining farms does not mean hiding them. For every lot we can document which villages contributed, the drying dates, the moisture readings at packing, and the cupping results. Buyers who want more detail — down to individual farm partners, their plot sizes, and the varieties they grow — can request a full provenance report. It ships with the samples, not as a favour, but as a standard document.', 'Menggabungkan kebun tidak berarti menyembunyikannya. Untuk setiap lot kami dapat mendokumentasikan desa mana yang berkontribusi, tanggal penjemuran, pembacaan kadar air saat pengemasan, dan hasil cupping. Pembeli yang menginginkan detail lebih — hingga mitra kebun perorangan, ukuran lahan, dan varietas yang mereka tanam — dapat meminta laporan asal-usul lengkap. Laporan itu dikirim bersama sampel, bukan sebagai kebaikan, melainkan sebagai dokumen standar.'),
                    $this->content('p', 'That combination — a consistent blended profile on the surface, and full transparency underneath — is what modern specialty buying demands. Consistency for the roast plan, traceability for the marketing story, and a fixed geographic identity for both. Lintong Nihuta and Doloksanggul are two names for a single, well-documented place, and both of them deserve to be on the bag.', 'Kombinasi itu — profil campuran yang konsisten di permukaan, dan transparansi penuh di baliknya — adalah tuntutan pembelian spesialti modern. Konsistensi untuk rencana roasting, keterlacakan untuk cerita pemasaran, dan identitas geografis yang tetap untuk keduanya. Lintong Nihuta dan Doloksanggul adalah dua nama untuk satu tempat yang terdokumentasi dengan baik, dan keduanya pantas ada di kemasan.'),
                ],
                'published_at' => now()->subDays(12),
            ],
            [
                'slug' => 'why-moisture-content-matters',
                'category' => 'process',
                'cover' => '/images/add/sun-drying.jpg',
                'title' => ['en' => 'Why moisture content makes or breaks a lot', 'id' => 'Mengapa kadar air menentukan nasib sebuah lot'],
                'excerpt' => ['en' => 'The single number that decides whether your green beans arrive bright and fresh — or moldy and stale.', 'id' => 'Satu angka yang menentukan apakah green bean Anda tiba cerah dan segar — atau berjamur dan basi.'],
                'content' => [
                    $this->content('p', 'Moisture content is the most important number on any green coffee spec sheet, and the one buyers most often forget to verify. It is also the number most responsible for the difference between a container that arrives bright and fresh and one that arrives musty, moldy, or stale. It affects everything that happens between the drying patio and your roaster — the weight you pay for, the shelf life you get, and the cup quality you can expect.', 'Kadar air adalah angka terpenting di spec sheet green coffee, dan yang paling sering lupa diverifikasi pembeli. Angka ini juga yang paling menentukan perbedaan antara kontainer yang tiba cerah dan segar dan kontainer yang tiba apek, berjamur, atau basi. Kadar air memengaruhi semua yang terjadi antara terpal pengeringan dan roaster Anda — berat yang Anda bayar, masa simpan yang Anda dapat, dan mutu cangkir yang bisa Anda harapkan.'),
                    $this->content('p', 'To understand why, it helps to remember that green coffee is not an inert product. The bean is a seed — alive, breathing, and slowly exchanging moisture with the air around it. Everything the exporter does to it after drying is about keeping that seed safely asleep until the roaster wakes it up. Moisture content is the dial that controls whether it sleeps well or starts to deteriorate.', 'Untuk memahami alasannya, perlu diingat bahwa green coffee bukan produk yang inert. Biji adalah benih — hidup, bernapas, dan perlahan bertukar kelembapan dengan udara di sekitarnya. Segala yang dilakukan eksportir setelah pengeringan adalah menjaga benih itu tetap tertidur dengan aman sampai roaster membangunkannya. Kadar air adalah kenop yang mengontrol apakah benih itu tidur nyenyak atau mulai membusuk.'),
                    $this->content('h2', 'The shipping window', 'Jendela kadar air kirim'),
                    $this->content('p', 'Green coffee ships safely at 10.5–11.5% moisture. This window is narrow for a reason. Above 12%, the bean is wet enough that mold and ochratoxin — a mycotoxin regulated by food safety authorities in most importing countries — become real risks during weeks inside a sealed container that sits on ships crossing the equator. Moisture migrates inside the bag, condensation forms, and what was a beautiful lot at origin can be a health hazard at the destination port.', 'Green coffee dikirim dengan aman pada 10,5–11,5% kadar air. Jendela ini sempit karena suatu alasan. Di atas 12%, biji cukup basah sehingga jamur dan okratoksin — mikotoksin yang diatur otoritas keamanan pangan di sebagian besar negara pengimpor — menjadi risiko nyata selama berminggu-minggu di dalam kontainer tertutup yang melintasi khatulistiwa. Kelembapan bermigrasi di dalam kantong, kondensasi terbentuk, dan lot yang indah di origin bisa menjadi bahaya kesehatan di pelabuhan tujuan.'),
                    $this->content('p', 'Below 10%, the problems are quieter but just as real. The bean loses its green colour, becoming pale and brittle, and the cell structure begins to break down. These beans cup flat and woody, tasting past-crop even when they are fresh off the boat. Buyers sometimes assume that drier is safer, because the mold risk disappears — but they end up with a container of coffee that roasts unevenly and tastes like nothing.', 'Di bawah 10%, masalahnya lebih senyap tetapi sama nyatanya. Biji kehilangan warna hijaunya, menjadi pucat dan rapuh, dan struktur sel mulai rusak. Biji seperti ini terasa flat dan woody, seperti past-crop bahkan ketika baru turun dari kapal. Pembeli kadang berasumsi bahwa lebih kering lebih aman, karena risiko jamur hilang — tetapi mereka berakhir dengan kontainer kopi yang roastingnya tidak merata dan rasanya hambar.'),
                    $this->content('h2', 'How we control it', 'Bagaimana kami mengontrolnya'),
                    $this->content('p', 'Every drying batch at our partner mills is measured regularly with calibrated moisture meters, not guessed by hand feel. Lots are only milled and packed once they stabilise inside the 10.5–11.5% window, and each bag gets a GrainPro hermetic liner to protect it from the humidity swings of ocean transit. The liner does not fix a wet lot — it preserves a correct one.', 'Setiap batch pengeringan di pabrik mitra kami diukur secara rutin dengan moisture meter terkalibrasi, bukan ditebak dengan meraba tangan. Lot baru dimiling dan dikemas setelah stabil di dalam jendela 10,5–11,5%, dan setiap kantong mendapat liner hermetik GrainPro untuk melindunginya dari perubahan kelembapan selama pelayaran. Liner tidak memperbaiki lot yang basah — liner menjaga lot yang sudah benar.'),
                    $this->content('p', 'When you receive a sample from us, it comes with a moisture reading taken at packing, on the actual lot you are evaluating. That number, together with the cupping report, tells you most of what you need to know about whether the container will arrive the way the sample tasted. If a supplier cannot tell you the moisture content of the lot they are selling, treat that as the warning it is.', 'Ketika Anda menerima sampel dari kami, sampel itu disertai pembacaan kadar air yang diambil saat pengemasan, pada lot yang benar-benar Anda evaluasi. Angka itu, bersama laporan cupping, memberi tahu hampir semua yang perlu Anda ketahui tentang apakah kontainer akan tiba seperti rasa sampelnya. Jika pemasok tidak bisa memberi tahu kadar air lot yang mereka jual, anggaplah itu sebagai peringatan.'),
                ],
                'published_at' => now()->subDays(14),
            ],
            [
                'slug' => 'how-to-store-green-coffee',
                'category' => 'market',
                'cover' => '/images/add/warehouse-1.jpg',
                'title' => ['en' => 'How to store green coffee (and keep it fresh)', 'id' => 'Cara menyimpan green coffee (agar tetap segar)'],
                'excerpt' => ['en' => 'Green beans are living, breathing cargo. Five rules that keep them roasting well months after arrival.', 'id' => 'Green bean adalah kargo yang hidup dan bernapas. Lima aturan agar tetap bagus diroasting berbulan-bulan setelah tiba.'],
                'content' => [
                    $this->content('p', 'Green coffee does not expire quickly, but it does age — and how it ages is almost entirely in the hands of whoever stores it. Stored badly, a beautiful 86-point lot can cup like a commercial blend within months. Stored well, the same lot can hold its profile for a year or more. This is not a mystery: green beans are hygroscopic, which means they constantly absorb and release moisture from the air around them, and that exchange drives nearly every form of quality loss.', 'Green coffee tidak cepat kedaluwarsa, tapi menua — dan bagaimana ia menua hampir sepenuhnya berada di tangan siapa pun yang menyimpannya. Disimpan buruk, lot indah bernilai 86 poin bisa terasa seperti kopi komersial dalam beberapa bulan. Disimpan baik, lot yang sama bisa mempertahankan profilnya selama setahun atau lebih. Ini bukan misteri: green bean bersifat higroskopis, artinya ia terus-menerus menyerap dan melepaskan kelembapan dari udara di sekitarnya, dan pertukaran itulah yang mendorong hampir semua bentuk penurunan mutu.'),
                    $this->content('p', 'The good news is that proper storage is mostly common sense once you understand what the bean is sensitive to. It is sensitive to heat, moisture, light, odours, and time. Control those five things and you have effectively frozen the aging clock. Here are the five rules we give to every roastery that buys from us.', 'Kabar baiknya, penyimpanan yang benar sebagian besar hanya akal sehat begitu Anda memahami apa yang sensitif bagi biji. Ia sensitif terhadap panas, kelembapan, cahaya, bau, dan waktu. Kendalikan lima hal itu dan Anda pada dasarnya menghentikan jam penuaan. Inilah lima aturan yang kami berikan kepada setiap roastery yang membeli dari kami.'),
                    $this->content('h2', 'The five rules', 'Lima aturannya'),
                    $this->content('p', 'First, keep the beans below 25°C and away from direct sun — heat accelerates every degradation reaction in the seed. Second, keep relative humidity under 70% and the floor dry; never store bags directly on concrete, because concrete wicks moisture and will wet the bottom of the bags. Third, keep the warehouse ventilated but sealed against rain and humidity spikes; still air is fine, wet air is not.', 'Pertama, jaga suhu di bawah 25°C dan jauhkan dari sinar matahari langsung — panas mempercepat setiap reaksi degradasi pada biji. Kedua, jaga kelembapan relatif di bawah 70% dan lantai tetap kering; jangan pernah meletakkan kantong langsung di beton, karena beton menyerap air dan akan membasahi dasar kantong. Ketiga, pastikan gudang berventilasi namun tertutup dari hujan dan lonjakan kelembapan; udara diam itu baik, udara basah tidak.'),
                    $this->content('p', 'Fourth, rotate stock: roast the oldest bags first, and label every delivery with its arrival date so the rotation is not guesswork. And fifth, treat the liner as part of the packaging: once a GrainPro liner is opened, the coffee is exposed, so re-seal it tightly and use the bag within a reasonable window. Many roasters buy in bulk precisely to save money, then lose the savings by opening ten bags at once and letting six of them go stale.', 'Keempat, putar stok: roasting kantong tertua lebih dulu, dan beri label setiap kiriman dengan tanggal kedatangannya agar perputaran tidak mengandalkan tebakan. Dan kelima, perlakukan liner sebagai bagian dari kemasan: begitu liner GrainPro dibuka, kopi terpapar, jadi tutup kembali dengan rapat dan gunakan kantong itu dalam jangka waktu yang wajar. Banyak roaster membeli dalam jumlah besar justru untuk menghemat, lalu kehilangan penghematan itu dengan membuka sepuluh kantong sekaligus dan membiarkan enam di antaranya basi.'),
                    $this->content('h2', 'How long does it last?', 'Berapa lama masa simpannya?'),
                    $this->content('p', 'In hermetic GrainPro liners, our lots hold their cup profile for 12 months or more, because the liner stops the bean from exchanging moisture with the outside world. Off the liner — in a standard jute bag or an opened and re-sealed liner — expect meaningful fading after 4–6 months in tropical conditions, and faster in humid climates. The bean does not go bad all at once; it goes flat gradually, losing aromatics first and sweetness later.', 'Dalam liner hermetik GrainPro, lot kami menjaga profil cangkirnya selama 12 bulan atau lebih, karena liner menghentikan pertukaran kelembapan biji dengan dunia luar. Tanpa liner — dalam kantong jute standar atau liner yang sudah dibuka dan ditutup kembali — penurunan rasa mulai terasa setelah 4–6 bulan di iklim tropis, dan lebih cepat di iklim lembap. Biji tidak rusak sekaligus; ia menjadi flat secara bertahap, kehilangan aromatik lebih dulu dan rasa manis kemudian.'),
                    $this->content('p', 'Always ask how your beans were packed before the container left origin, and factor that answer into your inventory planning. A lot that arrives in hermetic liners can be bought confidently in larger volume; a lot that arrives loose in jute should be roasted through quickly. Buying decisions should include the storage conversation, not just the price per kilogram.', 'Selalu tanyakan bagaimana biji Anda dikemas sebelum kontainer meninggalkan origin, dan masukkan jawaban itu ke dalam perencanaan inventaris Anda. Lot yang tiba dalam liner hermetik bisa dibeli dengan percaya diri dalam volume lebih besar; lot yang tiba longgar dalam jute sebaiknya segera diroasting. Keputusan pembelian seharusnya mencakup percakapan tentang penyimpanan, bukan hanya harga per kilogram.'),
                ],
                'published_at' => now()->subDays(18),
            ],
            [
                'slug' => 'green-coffee-sample-shipment-guide',
                'category' => 'market',
                'cover' => '/images/real/pouchgreenbeans.jpeg',
                'title' => ['en' => 'Sampling green coffee: from 500g pouch to full container', 'id' => 'Sampling green coffee: dari kantong 500g ke kontainer penuh'],
                'excerpt' => ['en' => 'How to evaluate samples properly before committing to 19 tons. A practical workflow for roasters.', 'id' => 'Cara mengevaluasi sampel dengan benar sebelum mengambil 19 ton. Alur praktis untuk roaster.'],
                'content' => [
                    $this->content('p', 'No serious buyer commits to a container blind. Between the farm in the Sumatran highlands and your cupping table sits a gap of geography, logistics, and trust — and the sample exists to close that gap. But a sample is only as useful as the discipline applied to it. Open it lazily, roast it casually, cup it alone, and it will tell you almost nothing. Evaluate it properly, and 500 grams of coffee can save you from a 19-ton mistake.', 'Tidak ada pembeli serius yang mengambil kontainer tanpa coba dulu. Di antara kebun di dataran tinggi Sumatra dan meja cupping Anda ada jarak geografi, logistik, dan kepercayaan — dan sampel hadir untuk menutup jarak itu. Tetapi sampel hanya berguna sejauh disiplin yang diterapkan padanya. Membukanya dengan malas, menyangrainya dengan asal, mencicipinya sendirian, maka sampel itu hampir tidak memberi tahu apa pun. Evaluasi dengan benar, dan 500 gram kopi bisa menyelamatkan Anda dari kesalahan 19 ton.'),
                    $this->content('p', 'The stakes are higher than they look. A container of green coffee is roughly 320 bags, representing a significant financial commitment, months of your roast plan, and the experience of every customer who drinks it. Sampling well is not bureaucratic caution — it is the cheapest insurance policy in the specialty coffee business.', 'Taruhannya lebih tinggi dari yang terlihat. Satu kontainer green coffee berisi sekitar 320 kantong, mewakili komitmen finansial yang besar, berbulan-bulan rencana roasting Anda, dan pengalaman setiap pelanggan yang meminumnya. Sampling yang baik bukan kehati-hatian birokratis — ia adalah polis asuransi termurah dalam bisnis kopi spesialti.'),
                    $this->content('h2', 'What to ask for', 'Apa yang perlu diminta'),
                    $this->content('p', 'Ask for a 500g–1kg sample of the current lot — not a leftover from last season — plus its cupping report, moisture reading, and screen analysis. A good exporter sends all four without being chased, because a sample without documentation only tells you half the story. We ship samples worldwide via DHL/FedEx, vacuum-sealed to protect freshness, and every sample pouch is tagged with the exact lot code it represents so there is no ambiguity about what you are evaluating.', 'Minta sampel 500g–1kg dari lot terkini — bukan sisa musim lalu — beserta laporan cupping, angka kadar air, dan analisis screen. Eksportir yang baik mengirim keempatnya tanpa perlu dikejar, karena sampel tanpa dokumentasi hanya memberi tahu setengah cerita. Kami mengirim sampel ke seluruh dunia via DHL/FedEx, disegel vakum untuk menjaga kesegaran, dan setiap kantong sampel diberi label kode lot yang persis diwakilinya sehingga tidak ada ambiguitas tentang apa yang Anda evaluasi.'),
                    $this->content('p', 'If a supplier hesitates to share the moisture reading or the cupping date, treat that as information in itself. The documents tell you not just about this lot, but about how the exporter operates. A supplier who volunteers full data is confident in what they are shipping; a supplier who has to be coaxed into providing it is usually hiding a reason.', 'Jika pemasok ragu membagikan angka kadar air atau tanggal cupping, anggaplah itu sebagai informasi tersendiri. Dokumen memberi tahu Anda bukan hanya tentang lot ini, tetapi tentang cara eksportir beroperasi. Pemasok yang sukarela memberikan data lengkap percaya diri pada apa yang mereka kirim; pemasok yang harus dibujuk untuk memberikannya biasanya menyembunyikan alasan.'),
                    $this->content('h2', 'How to cup it', 'Cara meng-cupping-nya'),
                    $this->content('p', 'Roast the sample to a light-medium profile — the range that lets origin character show — and rest it for at least a day before cupping. Cup it against your reference coffees rather than alone, because a coffee tasted in isolation has no baseline. Use the same grinder setting, water temperature, and steep time you use for every other lot, so the results are comparable across your whole purchasing history.', 'Roast sampel dengan profil light-medium — kisaran yang memungkinkan karakter origin tampil — dan diamkan setidaknya sehari sebelum cupping. Cupping berdampingan dengan kopi referensi Anda, bukan sendirian, karena kopi yang dicicipi dalam isolasi tidak punya dasar pembanding. Gunakan setting grinder, suhu air, dan waktu seduh yang sama seperti yang Anda pakai untuk lot lain, agar hasilnya bisa dibandingkan dengan seluruh riwayat pembelian Anda.'),
                    $this->content('p', 'Score it like any other lot, with the same score sheet and the same vocabulary, and if the decision is big, compare across at least two roast dates. Roast variation can flatter or punish a coffee unfairly; a lot that performs consistently across separate roasts is telling you something more reliable than a single lucky batch. Write down your scores before you look at the exporter\'s cupping report, so your palate is not biased by theirs.', 'Beri skor seperti lot lainnya, dengan lembar skor dan kosakata yang sama, dan jika keputusannya besar, bandingkan dari minimal dua tanggal roast. Variasi roast bisa menyanjung atau menghukum kopi secara tidak adil; lot yang tampil konsisten di beberapa roast terpisah memberi tahu sesuatu yang lebih andal daripada satu batch yang beruntung. Tulis skor Anda sebelum melihat laporan cupping eksportir, agar langit-langit mulut Anda tidak dipengaruhi oleh skor mereka.'),
                    $this->content('h2', 'From sample to contract', 'Dari sampel ke kontrak'),
                    $this->content('p', 'Once a lot passes your table, the critical question is continuity: will the container taste like the sample? The answer lies in lot discipline. When you order from us, we lock the container to the same lot code the sample came from — not to a newer, unverified delivery that happens to be in the warehouse. The coffee you cupped is the coffee you get, or we tell you before you commit that the lot has changed.', 'Begitu lot lolos di meja Anda, pertanyaan kritisnya adalah kesinambungan: akankah kontainer terasa seperti sampelnya? Jawabannya terletak pada disiplin lot. Ketika Anda memesan dari kami, kami mengunci kontainer ke kode lot yang sama dengan asal sampel — bukan ke kiriman baru yang belum terverifikasi yang kebetulan ada di gudang. Kopi yang Anda cupping adalah kopi yang Anda dapat, atau kami memberi tahu Anda sebelum Anda berkomitmen bahwa lotnya telah berubah.'),
                    $this->content('p', 'That guarantee is the whole point of traceability, and it is also the reason we recommend sampling even for repeat buyers. Crops change with the season, and a lot that was perfect six months ago may have shifted. The sample is not paperwork — it is the first delivery of every contract, and the exporter who treats it that way is the exporter worth shipping with.', 'Jaminan itulah inti dari keterlacakan, dan itu juga alasan kami menyarankan sampling bahkan untuk pembeli lama. Panen berubah mengikuti musim, dan lot yang sempurna enam bulan lalu mungkin sudah bergeser. Sampel bukan formalitas — ia adalah kiriman pertama dari setiap kontrak, dan eksportir yang memperlakukannya seperti itu adalah eksportir yang layak diajak bekerja sama.'),
                ],
                'published_at' => now()->subDays(21),
            ],
            [
                'slug' => 'export-documentation-explained',
                'category' => 'market',
                'cover' => '/images/add/warehouse-stacking.jpg',
                'title' => ['en' => 'Export documentation, explained', 'id' => 'Dokumentasi ekspor, dijelaskan'],
                'excerpt' => ['en' => 'The four documents behind every Indonesian coffee shipment — and what each one actually protects you from.', 'id' => 'Empat dokumen di balik setiap kiriman kopi Indonesia — dan dari apa masing-masing melindungi Anda.'],
                'content' => [
                    $this->content('p', 'Export paperwork looks intimidating until you realise that each document answers one specific question. A stack of unfamiliar certificates seems designed to confuse, but every sheet in the file exists because a customs officer, a banker, or an insurer somewhere needs a verifiable answer to a single question: Is this shipment what it claims to be? Once you understand what each document is for, the whole folder becomes readable — and you can spot at a glance whether an exporter knows what they are doing.', 'Dokumen ekspor terlihat menakutkan sampai Anda menyadari bahwa setiap dokumen menjawab satu pertanyaan spesifik. Tumpukan sertifikat yang tidak familiar tampak dirancang untuk membingungkan, tetapi setiap lembar di dalam map itu ada karena seorang petugas bea cukai, bankir, atau asuransi di suatu tempat membutuhkan jawaban terverifikasi atas satu pertanyaan: Apakah kiriman ini benar-benar seperti yang diklaim? Begitu Anda memahami fungsi setiap dokumen, seluruh map menjadi bisa dibaca — dan Anda bisa langsung melihat apakah seorang eksportir tahu apa yang mereka lakukan.'),
                    $this->content('p', 'There are four core documents behind every coffee shipment out of Indonesia, and understanding them matters more than it first appears. Clean documentation means no demurrage fees at the destination port, no customs delays, no disputes with your bank over a letter of credit, and no insurance headaches if something goes wrong in transit. Bad documentation can strand a perfectly good container of coffee in a foreign port for weeks.', 'Ada empat dokumen inti di balik setiap kiriman kopi dari Indonesia, dan memahaminya lebih penting daripada yang terlihat. Dokumentasi yang rapi berarti tidak ada biaya demurrage di pelabuhan tujuan, tidak ada penundaan bea cukai, tidak ada sengketa dengan bank Anda soal letter of credit, dan tidak ada sakit kepala asuransi jika terjadi sesuatu di perjalanan. Dokumentasi yang buruk bisa membuat kontainer kopi yang sempurna terdampar di pelabuhan asing selama berminggu-minggu.'),
                    $this->content('h2', 'The four documents', 'Empat dokumen itu'),
                    $this->content('p', 'The phytosanitary certificate proves the beans were inspected by the plant protection authority at origin and found free from pests and diseases — your customs office will require it before the container is released. It is issued by the Indonesian Agricultural Quarantine Agency after inspecting the actual lot, and its presence tells you the shipment passed an official health check at origin.', 'Sertifikat phytosanitary membuktikan biji telah diperiksa oleh otoritas perlindungan tanaman di origin dan dinyatakan bebas dari hama dan penyakit — kantor bea cukai Anda akan mewajibkannya sebelum kontainer dilepaskan. Dokumen ini diterbitkan oleh Badan Karantina Pertanian Indonesia setelah memeriksa lot yang sebenarnya, dan kehadirannya memberi tahu Anda bahwa kiriman itu lulus pemeriksaan kesehatan resmi di origin.'),
                    $this->content('p', 'The certificate of origin qualifies the shipment for preferential tariff treatment under trade agreements — a document that can be worth real money depending on your country\'s import duties on coffee. The commercial invoice states the value you are paying, and it must match the declared customs value exactly; discrepancies here are the most common trigger for customs inspection and fines. The packing list details bags, weights, container numbers, and marks — the factual inventory that every other document refers back to.', 'Certificate of origin memberi akses perlakuan tarif preferensial sesuai perjanjian dagang — dokumen yang bisa bernilai uang nyata tergantung bea masuk kopi di negara Anda. Commercial invoice menyatakan nilai yang Anda bayar, dan harus persis cocok dengan nilai pabean yang dideklarasikan; ketidaksesuaian di sini adalah pemicu paling umum inspeksi dan denda bea cukai. Packing list merinci kantong, berat, nomor kontainer, dan tanda — inventaris faktual yang dirujuk oleh semua dokumen lain.'),
                    $this->content('h2', 'Why it matters to you', 'Mengapa ini penting bagi Anda'),
                    $this->content('p', 'As a buyer, you rarely see most of this paperwork until the shipment is already on the water — but you feel its quality immediately when the container arrives. A shipment with clean documentation clears customs in days, arrives at your warehouse on schedule, and gives your bank and insurer everything they need to process the payment without friction. A shipment with sloppy documentation sits in the port, accruing storage charges, while your roaster stands idle waiting for beans you have already paid for.', 'Sebagai pembeli, Anda jarang melihat sebagian besar dokumen ini sampai kiriman sudah di laut — tetapi Anda langsung merasakan kualitasnya ketika kontainer tiba. Kiriman dengan dokumentasi rapi lolos bea cukai dalam hitungan hari, tiba di gudang Anda sesuai jadwal, dan memberi bank serta asuransi semua yang mereka butuhkan untuk memproses pembayaran tanpa gesekan. Kiriman dengan dokumentasi asal-asalan terdampar di pelabuhan, menumpuk biaya penyimpanan, sementara roaster Anda menganggur menunggu biji yang sudah Anda bayar.'),
                    $this->content('p', 'We prepare and double-check every document before the container moves, and a copy of the full file travels with the shipment and is emailed to the buyer the same day. That is not bureaucracy for its own sake — at origin, the paperwork is the product. The coffee will speak for itself when it is roasted; the documents are what get it there in the first place.', 'Kami menyiapkan dan memeriksa ulang setiap dokumen sebelum kontainer bergerak, dan salinan seluruh map ikut dalam kiriman serta dikirim email ke pembeli di hari yang sama. Itu bukan birokrasi untuk birokrasi — di origin, dokumennya adalah produknya. Kopi akan berbicara sendiri ketika diroasting; dokumenlah yang membawanya ke sana sejak awal.'),
                ],
                'published_at' => now()->subDays(28),
            ],
        ];

        foreach ($posts as $post) {
            $category = Category::where('slug', $post['category'])->first();
            Post::updateOrCreate(
                ['slug' => $post['slug']],
                [
                    'category_id' => $category?->id,
                    'title' => $post['title'],
                    'excerpt' => $post['excerpt'],
                    'content' => $post['content'],
                    'cover_image' => $post['cover'],
                    'featured' => false,
                    'published_at' => $post['published_at'],
                ],
            );
        }
    }
}
